export const TODOACTIONS = {
    ADD_TODO: 'ADD_TODO',
    TOGGLE_TODO: 'TOGGLE_TODO',
    REMOVE_TODO: 'REMOVE_TODO',
    REMOVE_ALL_TODOS: 'REMOVE_ALL_TODOS'
};

export const COUNTERACTIONS = {
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT'
};
